version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=0812
      - DB_NAME=smartfinancer
      - DB_PORT=5432
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0812
      POSTGRES_DB: smartfinancer
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres-data:
